export const COURSE = {
  title: "Inteligencia artificial aplicada a la práctica contable",
  hours: 40,
  weeks: 10,
  guidedHoursPerWeek: 3,
  independentHoursPerWeek: 1,
};

const guide = (opening, steps, checkpoint, deliverable) => ({ opening, steps, checkpoint, deliverable });

export const courseModules = [
  {
    id: "modulo-01", week: 1, hours: 4,
    title: "Qué es la IA y qué es un prompt",
    focus: "Entender, con ejemplos sencillos, qué es la IA generativa, qué es un prompt y por qué una respuesta necesita revisión profesional.",
    outcome: "Explicar con sus propias palabras qué es un prompt y distinguir una instrucción clara de una petición ambigua.",
    exerciseIds: ["prompt"], materialPath: "/docs/curso/modulo-01/README.md",
    guide: guide("Antes de diseñar un prompt, Nora te explica qué significa pedir algo a una IA y qué puede salir mal.", ["Conoce la diferencia entre IA generativa, automatización y una respuesta humana.", "Aprende que un prompt es la instrucción que orienta la respuesta.", "Prueba una petición simple y señala qué dato o resultado habría que revisar."], "¿Puedes explicar qué le estás pidiendo a la IA, con qué datos y cómo comprobarías su respuesta?", "Explicación breve de ‘prompt’ y comparación entre una petición ambigua y una instrucción clara."),
    teachFirst: { why: "La IA no decide por ti: genera una propuesta a partir de una instrucción; el prompt es justamente esa instrucción.", concepts: [["IA generativa", "produce texto o propuestas nuevas a partir de patrones; puede equivocarse."], ["Prompt", "instrucción o petición que le das a una herramienta de IA."], ["Respuesta", "propuesta que debes leer, contrastar y revisar; no es una verdad automática."],], example: "Ejemplo: ‘ayúdame con contabilidad’ es un prompt muy amplio; ‘explica esta diferencia usando solo estos datos ficticios’ orienta mejor la respuesta." },
    toolkit: [{ name: "NotebookLM", role: "Aprender con fuentes", activity: "Carga una guía ficticia y pregunta: ‘¿qué es un prompt y qué partes tiene?’.", guardrail: "Usa solo documentos educativos o ficticios.", url: "https://notebooklm.google/?hl=es" }, { name: "Claude", role: "Explicar en lenguaje sencillo", activity: "Pide una explicación para una persona que nunca ha usado IA y compárala con tu definición.", guardrail: "No subas datos reales ni aceptes la explicación sin revisarla.", url: "https://claude.ai/" }],
    demonstration: { before: "Analiza esto.", after: "Explica con palabras sencillas qué es un prompt y señala qué datos ficticios necesitarías para clasificar una compra.", why: "La segunda petición dice qué aprender, qué observar y qué información puede usar la herramienta." },
    context: { documents: ["Una descripción breve de una tarea contable o administrativa que quieras entender."], mustContain: ["Objetivo de la tarea", "Quién revisará la respuesta", "Un ejemplo ficticio de entrada"], format: "Texto, PDF o una nota de 5 a 10 líneas.", protect: "No incluyas nombres, importes reales ni información de clientes." },
  },
  {
    id: "modulo-02", week: 2, hours: 4,
    title: "Diseño de instrucciones contables",
    focus: "Construir prompts con contexto, datos permitidos, tarea, formato, restricciones y verificación; iterar con una rúbrica.",
    outcome: "Entregar una plantilla de prompt y una versión revisada con criterios visibles.",
    exerciseIds: ["prompt"], materialPath: "/docs/curso/modulo-02/README.md",
    guide: guide("Un prompt útil funciona como una hoja de trabajo: define el alcance antes de pedir una respuesta.", ["Especifica rol, contexto y datos ficticios permitidos.", "Pide una salida concreta que otra persona pueda revisar.", "Añade límites, dudas y una comprobación final."], "¿Tu instrucción permite distinguir hechos, supuestos y datos faltantes?", "Plantilla de prompt contable y una iteración mejorada."),
    teachFirst: { why: "Una instrucción clara reduce ambigüedad y hace que la respuesta sea revisable.", concepts: [["Prompt", "instrucción que orienta una respuesta de IA."], ["Contexto", "datos y propósito necesarios para entender la tarea."], ["Restricción", "límite que evita inventar, exceder el alcance o exponer datos."],], example: "Ejemplo: no es igual pedir ‘analiza esto’ que pedir ‘compara estos movimientos ficticios y devuelve una tabla con dudas’." },
    toolkit: [{ name: "Claude", role: "Construir instrucciones", activity: "Pide tres versiones de un prompt contable y evalúalas con la rúbrica del módulo.", guardrail: "La salida es un borrador; verifica contexto, límites y formato.", url: "https://claude.ai/" }, { name: "NotebookLM", role: "Anclar conceptos", activity: "Consulta las fuentes del módulo y pide que señale qué afirmaciones están respaldadas.", guardrail: "Comprueba que la fuente sea pertinente y vigente.", url: "https://notebooklm.google/?hl=es" }],
    demonstration: { before: "Haz un prompt mejor.", after: "Actúa como tutor contable. Con estos datos ficticios, redacta un prompt que pida clasificación, formato de tabla y una lista de datos faltantes. No inventes información.", why: "La instrucción mejorada define contexto, tarea, formato y límites." },
    context: { documents: ["Un caso ficticio y, si tienes, una rúbrica o formato de salida esperado."], mustContain: ["Contexto", "Tarea concreta", "Formato de respuesta", "Límites y datos faltantes"], format: "Documento de texto, PDF, hoja de cálculo o plantilla.", protect: "Sustituye nombres y cifras reales por etiquetas y valores simulados." },
  },
  {
    id: "modulo-03", week: 3, hours: 4,
    title: "Herramientas, privacidad y uso seguro",
    focus: "Comparar herramientas según la tarea, reconocer datos personales y confidenciales, y revisar permisos antes de compartir información.",
    outcome: "Completar una matriz de selección de herramienta y una lista de control de privacidad.",
    exerciseIds: ["nomina"], materialPath: null,
    guide: guide("La primera decisión no es qué herramienta usar, sino qué datos nunca debes compartir.", ["Identifica datos personales, confidenciales y ficticios.", "Define el propósito, permisos y retención necesarios.", "Redacta una regla de minimización y una ruta de escalamiento."], "¿Podrías explicar por qué cada campo es necesario para la tarea?", "Matriz de herramienta y checklist de privacidad antes de compartir."),
    teachFirst: { why: "La herramienta adecuada no compensa compartir datos que no son necesarios o seguros.", concepts: [["Dato personal", "información que identifica o puede identificar a una persona."], ["Minimización", "compartir solo lo indispensable para la tarea."], ["Permiso", "autoridad y configuración que determinan qué puede hacer una herramienta."],], example: "Ejemplo: para practicar nómina se usan campos ficticios; no se necesitan nombres, CURP ni cuentas reales." },
    toolkit: [{ name: "NotebookLM", role: "Ordenar políticas", activity: "Construye un cuaderno con políticas ficticias y pregunta qué datos deben protegerse.", guardrail: "Nunca uses expedientes reales de clientes o empleados.", url: "https://notebooklm.google/?hl=es" }, { name: "n8n", role: "Diseñar controles", activity: "Dibuja un flujo ficticio que detenga datos sensibles y solicite aprobación humana.", guardrail: "Prueba con datos simulados y revisa permisos antes de conectar servicios.", url: "https://n8n.io/" }],
    demonstration: { before: "Sube la nómina para que la IA la revise.", after: "Usa campos ficticios y elimina identificadores. Detén el flujo si aparece un dato personal y solicita revisión humana.", why: "La seguridad se diseña antes de compartir o automatizar." },
    context: { documents: ["Una política interna de manejo de datos o un formato de nómina de ejemplo."], mustContain: ["Campos necesarios", "Propósito de cada campo", "Quién puede acceder", "Qué debe aprobarse"], format: "PDF, documento o tabla ficticia.", protect: "Elimina nombre, CURP, RFC, cuenta bancaria, domicilio y cualquier identificador." },
  },
  {
    id: "modulo-04", week: 4, hours: 4,
    title: "Preparación de datos y clasificación",
    focus: "Revisar estructura y calidad de archivos; estandarizar campos; proponer categorías y apartar excepciones para revisión humana.",
    outcome: "Preparar un conjunto de práctica ordenado y un mapa de categorías con reglas y excepciones.",
    exerciseIds: ["clasificacion"], materialPath: null,
    guide: guide("La IA clasifica mejor cuando los datos tienen estructura y las excepciones están a la vista.", ["Revisa campos, formatos, duplicados y valores faltantes.", "Define categorías con una regla observable.", "Aparta casos ambiguos: no fuerces una clasificación."], "¿Qué dato te haría cambiar de categoría o pedir una revisión?", "Conjunto ordenado, mapa de categorías y lista de excepciones."),
    teachFirst: { why: "Una clasificación confiable empieza por datos legibles y reglas que otra persona pueda repetir.", concepts: [["Campo", "columna con un significado definido, como fecha o importe."], ["Categoría", "grupo asignado con una regla observable."], ["Excepción", "caso ambiguo que se aparta para revisión humana."],], example: "Ejemplo: si un concepto no permite saber si es gasto o activo, se marca como excepción en vez de adivinar." },
    toolkit: [{ name: "n8n", role: "Preparar datos", activity: "Crea un flujo de prueba que valide columnas, formatos y excepciones de un CSV ficticio.", guardrail: "No automatices el descarte de filas ambiguas.", url: "https://n8n.io/" }, { name: "Claude", role: "Proponer categorías", activity: "Pide reglas de clasificación y casos límite para revisarlos manualmente.", guardrail: "Separa propuesta, regla y decisión final.", url: "https://claude.ai/" }],
    demonstration: { before: "Clasifica todas estas filas.", after: "Clasifica por regla observable; marca como excepción toda fila cuyo uso o concepto no pueda confirmarse.", why: "Una buena clasificación permite decir ‘no sé todavía’ sin forzar una categoría." },
    context: { documents: ["Un CSV o Excel de transacciones ficticias y un catálogo de categorías."], mustContain: ["Fecha", "Descripción o concepto", "Importe", "Regla o categoría esperada"], format: "CSV o XLSX; una fila por movimiento y encabezados claros.", protect: "No uses archivos descargados de un cliente sin anonimizar cada campo sensible." },
  },
  {
    id: "modulo-05", week: 5, hours: 4,
    title: "Conciliación y automatización de flujos",
    focus: "Comparar libro y banco, separar coincidencias y partidas pendientes, y definir controles en el flujo de trabajo.",
    outcome: "Documentar una conciliación y un procedimiento con entradas, revisión, autorización y registro.",
    exerciseIds: ["conciliacion"], materialPath: null,
    guide: guide("Conciliar no es buscar una cifra parecida: es explicar cada diferencia con evidencia y responsable.", ["Alinea fechas, conceptos e importes de ambas fuentes.", "Separa coincidencias, pendientes y posibles comisiones.", "Diseña revisión, autorización y registro de ajustes."], "¿Puedes señalar qué falta registrar sin convertir una hipótesis en hecho?", "Conciliación documentada y procedimiento con controles."),
    teachFirst: { why: "Una conciliación explica diferencias entre dos fuentes; no solo busca coincidencias.", concepts: [["Coincidencia", "movimiento que coincide por criterios definidos."], ["Partida pendiente", "diferencia que todavía requiere registro o evidencia."], ["Control", "punto de revisión, autorización o trazabilidad del ajuste."],], example: "Ejemplo: una comisión bancaria puede explicar una diferencia, pero debe confirmarse y registrarse con evidencia." },
    toolkit: [{ name: "n8n", role: "Orquestar conciliaciones", activity: "Modela un flujo que compare dos fuentes ficticias y envíe pendientes a revisión.", guardrail: "Incluye aprobación humana antes de registrar un ajuste.", url: "https://n8n.io/" }, { name: "Claude", role: "Explicar diferencias", activity: "Solicita hipótesis etiquetadas como hipótesis, no como conclusiones.", guardrail: "Confirma cada diferencia contra la evidencia original.", url: "https://claude.ai/" }],
    demonstration: { before: "Concilia el banco.", after: "Compara fecha, concepto e importe entre ambas fuentes; separa coincidencias, pendientes y ajustes que requieren autorización.", why: "El procedimiento define qué comparar y qué hacer con las diferencias." },
    context: { documents: ["Un estado de cuenta bancario y un libro auxiliar del mismo periodo, ambos de práctica."], mustContain: ["Fecha", "Referencia o concepto", "Importe", "Saldo o identificador de movimiento"], format: "Dos CSV/XLSX con la misma moneda y periodo.", protect: "Usa cuentas y referencias ficticias; no conectes banca en línea." },
  },
  {
    id: "modulo-06", week: 6, hours: 4,
    title: "Balanzas e indicadores financieros",
    focus: "Comprobar sumas, interpretar variaciones y diferenciar una inconsistencia aritmética de una explicación contable.",
    outcome: "Crear una hoja de revisión con diferencia, hipótesis permitidas y verificaciones siguientes.",
    exerciseIds: ["balanza"], materialPath: null,
    guide: guide("Primero comprueba la aritmética; después formula hipótesis y nunca al revés.", ["Verifica sumas, signo, periodo y unidades.", "Describe la variación sin atribuirle una causa no demostrada.", "Anota la evidencia que resolvería cada hipótesis."], "¿Qué cálculo puedes confirmar y qué explicación sigue abierta?", "Hoja de revisión con diferencia, hipótesis y próximas verificaciones."),
    teachFirst: { why: "Los números se interpretan después de comprobar el cálculo y el periodo al que pertenecen.", concepts: [["Diferencia", "resultado de comparar dos valores o totales."], ["Variación", "cambio observado entre periodos o saldos."], ["Hipótesis", "explicación provisional que todavía necesita evidencia."],], example: "Ejemplo: una variación no prueba por sí sola que exista un error; primero se revisan sumas, signo y periodo." },
    toolkit: [{ name: "Claude", role: "Explicar variaciones", activity: "Pide una explicación en dos columnas: cálculo observado y causas que aún deben investigarse.", guardrail: "No permitas que invente cifras o periodos.", url: "https://claude.ai/" }, { name: "n8n", role: "Comprobar reglas", activity: "Diseña validaciones simples para sumas, signos y campos faltantes.", guardrail: "Las validaciones no sustituyen la interpretación profesional.", url: "https://n8n.io/" }],
    demonstration: { before: "¿Por qué cambió el saldo?", after: "Comprueba primero sumas, signo y periodo. Después enumera hipótesis y la evidencia necesaria para confirmar cada una.", why: "Una explicación responsable distingue cálculo confirmado de causa pendiente." },
    context: { documents: ["Una balanza de comprobación y, si es posible, la balanza del periodo anterior."], mustContain: ["Cuenta", "Debe", "Haber o saldo", "Periodo y unidad monetaria"], format: "CSV, XLSX o tabla con totales verificables.", protect: "Sustituye razón social, RFC y cifras sensibles por datos simulados." },
  },
  {
    id: "modulo-07", week: 7, hours: 4,
    title: "Reportes y comunicación ejecutiva",
    focus: "Separar hechos, hipótesis, limitaciones y próximos pasos al convertir cifras en una explicación breve.",
    outcome: "Entregar un reporte ejecutivo de una página respaldado por los datos ficticios.",
    exerciseIds: ["reporte"], materialPath: null,
    guide: guide("Un reporte ejecutivo no dice todo: dice lo necesario, muestra el respaldo y deja claro qué falta.", ["Abre con el hallazgo y su impacto observable.", "Separa hechos, hipótesis y limitaciones.", "Cierra con una acción, responsable y fecha de revisión."], "¿Qué frase de tu reporte cambiaría si faltara una fuente?", "Reporte de una página con hechos, límites y próximos pasos."),
    teachFirst: { why: "Comunicar bien es distinguir lo que los datos muestran de lo que todavía se debe investigar.", concepts: [["Hecho", "afirmación respaldada directamente por los datos disponibles."], ["Hipótesis", "interpretación posible, todavía no confirmada."], ["Próximo paso", "acción concreta para reducir la incertidumbre."],], example: "Ejemplo: ‘el saldo bajó’ es un hecho; ‘bajó por un cobro duplicado’ es una hipótesis hasta revisar evidencia." },
    toolkit: [{ name: "NotebookLM", role: "Preparar un briefing", activity: "Reúne datos ficticios y fuentes del módulo para pedir un esquema con citas o referencias.", guardrail: "Distingue lo que está en las fuentes de lo que es interpretación.", url: "https://notebooklm.google/?hl=es" }, { name: "Claude", role: "Redactar con claridad", activity: "Convierte el esquema en un reporte de una página con hechos, límites y próximos pasos.", guardrail: "Revisa tono, cifras y destinatario antes de compartir.", url: "https://claude.ai/" }],
    demonstration: { before: "Escribe un reporte sobre estos números.", after: "Redacta un reporte de una página con hallazgo, impacto observable, limitaciones y un próximo paso con responsable.", why: "El formato ayuda a comunicar sin ocultar incertidumbre." },
    context: { documents: ["El conjunto de cifras o indicadores que quieres comunicar y el formato del reporte."], mustContain: ["Periodo", "Destinatario", "Fuente de cada cifra", "Decisión o acción esperada"], format: "PDF, documento, CSV o plantilla de una página.", protect: "Comparte solo un caso ficticio y revisa que el reporte no revele información confidencial." },
  },
  {
    id: "modulo-08", week: 8, hours: 4,
    title: "Auditoría, excepciones y anomalías",
    focus: "Usar patrones como señales para investigar, requerir evidencia y evitar conclusiones de fraude sin sustento.",
    outcome: "Documentar una anomalía con evidencia pendiente, riesgo y siguiente paso.",
    exerciseIds: ["analisis"], materialPath: null,
    guide: guide("Una anomalía es una señal de revisión, no una sentencia. Nora te ayudará a mantener esa diferencia.", ["Describe el patrón observado y su frecuencia.", "Estima el riesgo sin afirmar intención ni fraude.", "Pide evidencia, asigna un siguiente paso y conserva trazabilidad."], "¿Qué observaste directamente y qué estás suponiendo?", "Ficha de anomalía con evidencia pendiente, riesgo y acción."),
    teachFirst: { why: "Una anomalía activa una revisión; no autoriza a acusar fraude ni a concluir una causa.", concepts: [["Señal", "patrón que se aparta de lo esperado."], ["Riesgo", "posible impacto si la situación no se aclara."], ["Evidencia", "registro o fuente que permite confirmar o descartar una hipótesis."],], example: "Ejemplo: un importe inusual pide revisar la factura y el contexto; no demuestra intención indebida." },
    toolkit: [{ name: "n8n", role: "Escalar excepciones", activity: "Diseña un flujo que etiquete una anomalía y cree una tarea de revisión, sin acusar fraude.", guardrail: "No conectes notificaciones reales durante la práctica.", url: "https://n8n.io/" }, { name: "Claude", role: "Generar hipótesis", activity: "Pide hipótesis alternativas y la evidencia necesaria para cada una.", guardrail: "Una hipótesis no es un hallazgo confirmado.", url: "https://claude.ai/" }],
    demonstration: { before: "Detecta el fraude.", after: "Describe el patrón inusual, estima el riesgo sin afirmar intención y solicita la evidencia que permitiría investigarlo.", why: "Una anomalía inicia una revisión; no prueba por sí sola una conducta indebida." },
    context: { documents: ["Un registro ficticio de movimientos y una regla de lo que normalmente se espera."], mustContain: ["Patrón observado", "Frecuencia o línea base", "Criterio de excepción", "Evidencia disponible"], format: "CSV/XLSX más una nota que describa la línea base.", protect: "No etiquetes personas ni afirmes fraude; anonimiza todo identificador." },
  },
  {
    id: "modulo-09", week: 9, hours: 4,
    title: "Investigación fiscal responsable en México",
    focus: "Precisar ejercicio y régimen; identificar datos faltantes; contrastar publicaciones vigentes y pedir revisión profesional.",
    outcome: "Completar una hoja de verificación de fuentes, faltantes y límites de la respuesta.",
    exerciseIds: ["isr", "resico", "nomina"], materialPath: null,
    guide: guide("En temas fiscales, una respuesta prudente comienza declarando el periodo, régimen y datos que faltan.", ["Define el supuesto fiscal y la fecha de vigencia.", "Contrasta fuentes oficiales y registra la versión consultada.", "Señala límites y deriva a revisión profesional cuando corresponda."], "¿Qué dato o fuente faltante impide orientar de forma responsable?", "Hoja de fuentes, datos faltantes, límites y derivación."),
    teachFirst: { why: "Una orientación fiscal responsable depende del periodo, régimen, fuente vigente y datos concretos.", concepts: [["Periodo", "fecha o ejercicio al que aplica la regla consultada."], ["Régimen", "situación fiscal que cambia obligaciones y condiciones."], ["Fuente oficial", "publicación vigente que debe contrastarse y registrarse."],], example: "Ejemplo: la misma pregunta puede requerir una respuesta distinta si cambia el ejercicio o el régimen." },
    toolkit: [{ name: "NotebookLM", role: "Consultar fuentes", activity: "Carga únicamente publicaciones fiscales ficticias o fuentes oficiales seleccionadas y pregunta por diferencias de periodo.", guardrail: "Verifica vigencia, jurisdicción y régimen; no obtengas una conclusión automática.", url: "https://notebooklm.google/?hl=es" }, { name: "n8n", role: "Encaminar revisión", activity: "Modela un flujo que detenga respuestas fiscales incompletas y las derive a revisión.", guardrail: "No automatices declaraciones, cálculos ni envíos oficiales.", url: "https://n8n.io/" }],
    demonstration: { before: "¿Cuánto debo pagar de impuestos?", after: "Indica ejercicio, régimen, jurisdicción y datos faltantes; consulta fuentes oficiales vigentes y deriva la conclusión a revisión profesional.", why: "Una respuesta fiscal cambia con el periodo, el régimen y la fuente aplicable." },
    context: { documents: ["La fuente oficial o material fiscal que deseas estudiar y un caso hipotético."], mustContain: ["Ejercicio o fecha de vigencia", "Régimen", "Jurisdicción", "Datos faltantes y fuente consultada"], format: "Enlace o PDF oficial más una ficha del caso ficticio.", protect: "No uses declaraciones, constancias ni datos fiscales reales; la actividad no determina obligaciones." },
  },
  {
    id: "modulo-10", week: 10, hours: 4,
    title: "Asistentes, gobernanza y proyecto integrador",
    focus: "Diseñar un procedimiento reutilizable con entradas, salidas, salvaguardas, métricas, revisión humana y escalamiento.",
    outcome: "Presentar un flujo de trabajo documentado y un resumen ejecutivo sobre un caso totalmente ficticio.",
    exerciseIds: ["prompt", "clasificacion", "conciliacion", "balanza", "reporte", "analisis", "isr", "resico", "nomina"], materialPath: null,
    guide: guide("El proyecto integrador une criterio, datos, controles y comunicación en un flujo que otra persona pueda auditar.", ["Define entradas, salida esperada y puntos de control.", "Asigna revisión humana, métricas y criterios de escalamiento.", "Prueba el flujo con un caso ficticio y documenta sus límites."], "¿Qué ocurre cuando la IA no tiene evidencia suficiente o propone algo inesperado?", "Flujo gobernado, resumen ejecutivo y registro de decisiones."),
    teachFirst: { why: "Un asistente confiable necesita límites, revisión humana y una forma de demostrar qué ocurrió.", concepts: [["Entrada", "dato o documento permitido que inicia el flujo."], ["Salida", "resultado esperado con formato y criterios definidos."], ["Gobernanza", "reglas de revisión, métricas, permisos y escalamiento."],], example: "Ejemplo: si faltan datos, el flujo debe detenerse y pedir revisión, no completar silenciosamente." },
    toolkit: [{ name: "NotebookLM", role: "Consolidar conocimiento", activity: "Crea el cuaderno del proyecto con fuentes, decisiones y límites del caso ficticio.", guardrail: "Mantén trazabilidad de fuentes y no incluyas datos reales.", url: "https://notebooklm.google/?hl=es" }, { name: "Claude", role: "Revisar entregables", activity: "Pide una revisión contra la rúbrica: entradas, salidas, controles y escalamiento.", guardrail: "La revisión de Claude no reemplaza la aprobación del equipo.", url: "https://claude.ai/" }, { name: "n8n", role: "Prototipar el flujo", activity: "Construye un prototipo con datos ficticios, aprobación humana y registro de ejecuciones.", guardrail: "No conectes sistemas productivos ni credenciales reales.", url: "https://n8n.io/" }],
    demonstration: { before: "Automatiza todo el proceso.", after: "Define entrada, validaciones, salida, aprobación humana, registro de ejecución y condición de escalamiento antes de conectar cualquier sistema.", why: "Un flujo gobernado sabe cuándo continuar y cuándo detenerse." },
    context: { documents: ["Los documentos de los módulos anteriores y una descripción del flujo que quieres prototipar."], mustContain: ["Entradas", "Salidas", "Validaciones", "Aprobador humano", "Condición de escalamiento"], format: "Carpeta de documentos ficticios, diagrama o tabla de flujo.", protect: "No conectes credenciales, sistemas productivos, pagos ni envíos oficiales." },
  },
];
