export const COURSE = {
  title: "Inteligencia artificial aplicada a la práctica contable",
  hours: 40,
  weeks: 10,
  guidedHoursPerWeek: 3,
  independentHoursPerWeek: 1,
};

export const courseModules = [
  {
    id: "modulo-01", week: 1, hours: 4,
    title: "Fundamentos de IA y criterio profesional",
    focus: "Diferenciar automatización, modelos predictivos e IA generativa; reconocer errores, incertidumbre y necesidad de supervisión.",
    outcome: "Elaborar un mapa de tareas: qué puede apoyar una herramienta, qué debe verificarse y qué no conviene automatizar.",
    exerciseIds: ["prompt"],
    materialPath: "/docs/curso/modulo-01/README.md",
  },
  {
    id: "modulo-02", week: 2, hours: 4,
    title: "Diseño de instrucciones contables",
    focus: "Construir prompts con contexto, datos permitidos, tarea, formato, restricciones y verificación; iterar con una rúbrica.",
    outcome: "Entregar una plantilla de prompt y una versión revisada con criterios visibles.",
    exerciseIds: ["prompt"],
    materialPath: "/docs/curso/modulo-02/README.md",
  },
  {
    id: "modulo-03", week: 3, hours: 4,
    title: "Herramientas, privacidad y uso seguro",
    focus: "Comparar herramientas según la tarea, reconocer datos personales y confidenciales, y revisar permisos antes de compartir información.",
    outcome: "Completar una matriz de selección de herramienta y una lista de control de privacidad.",
    exerciseIds: ["nomina"],
    materialPath: null,
  },
  {
    id: "modulo-04", week: 4, hours: 4,
    title: "Preparación de datos y clasificación",
    focus: "Revisar estructura y calidad de archivos; estandarizar campos; proponer categorías y apartar excepciones para revisión humana.",
    outcome: "Preparar un conjunto de práctica ordenado y un mapa de categorías con reglas y excepciones.",
    exerciseIds: ["clasificacion"],
    materialPath: null,
  },
  {
    id: "modulo-05", week: 5, hours: 4,
    title: "Conciliación y automatización de flujos",
    focus: "Comparar libro y banco, separar coincidencias y partidas pendientes, y definir controles en el flujo de trabajo.",
    outcome: "Documentar una conciliación y un procedimiento con entradas, revisión, autorización y registro.",
    exerciseIds: ["conciliacion"],
    materialPath: null,
  },
  {
    id: "modulo-06", week: 6, hours: 4,
    title: "Balanzas e indicadores financieros",
    focus: "Comprobar sumas, interpretar variaciones y diferenciar una inconsistencia aritmética de una explicación contable.",
    outcome: "Crear una hoja de revisión con diferencia, hipótesis permitidas y verificaciones siguientes.",
    exerciseIds: ["balanza"],
    materialPath: null,
  },
  {
    id: "modulo-07", week: 7, hours: 4,
    title: "Reportes y comunicación ejecutiva",
    focus: "Separar hechos, hipótesis, limitaciones y próximos pasos al convertir cifras en una explicación breve.",
    outcome: "Entregar un reporte ejecutivo de una página respaldado por los datos ficticios.",
    exerciseIds: ["reporte"],
    materialPath: null,
  },
  {
    id: "modulo-08", week: 8, hours: 4,
    title: "Auditoría, excepciones y anomalías",
    focus: "Usar patrones como señales para investigar, requerir evidencia y evitar conclusiones de fraude sin sustento.",
    outcome: "Documentar una anomalía con evidencia pendiente, riesgo y siguiente paso.",
    exerciseIds: ["analisis"],
    materialPath: null,
  },
  {
    id: "modulo-09", week: 9, hours: 4,
    title: "Investigación fiscal responsable en México",
    focus: "Precisar ejercicio y régimen; identificar datos faltantes; contrastar publicaciones vigentes y pedir revisión profesional.",
    outcome: "Completar una hoja de verificación de fuentes, faltantes y límites de la respuesta.",
    exerciseIds: ["isr", "resico", "nomina"],
    materialPath: null,
  },
  {
    id: "modulo-10", week: 10, hours: 4,
    title: "Asistentes, gobernanza y proyecto integrador",
    focus: "Diseñar un procedimiento reutilizable con entradas, salidas, salvaguardas, métricas, revisión humana y escalamiento.",
    outcome: "Presentar un flujo de trabajo documentado y un resumen ejecutivo sobre un caso totalmente ficticio.",
    exerciseIds: ["prompt", "clasificacion", "conciliacion", "balanza", "reporte", "analisis", "isr", "resico", "nomina"],
    materialPath: null,
  },
];
