export const COURSE = {
  title: "Inteligencia artificial aplicada a la práctica contable",
  hours: 40,
  weeks: 10,
  guidedHoursPerWeek: 3,
  independentHoursPerWeek: 1,
};

const guide = (opening, steps, checkpoint, deliverable) => ({ opening, steps, checkpoint, deliverable });

export const courseModules = [
  {
    id: "modulo-01", week: 1, hours: 4,
    title: "Fundamentos de IA y criterio profesional",
    focus: "Diferenciar automatización, modelos predictivos e IA generativa; reconocer errores, incertidumbre y necesidad de supervisión.",
    outcome: "Elaborar un mapa de tareas: qué puede apoyar una herramienta, qué debe verificarse y qué no conviene automatizar.",
    exerciseIds: ["prompt"], materialPath: "/docs/curso/modulo-01/README.md",
    guide: guide("Antes de pensar en una herramienta, delimita la decisión contable y el riesgo de equivocarte.", ["Separa tarea, datos y decisión final.", "Clasifica qué puede proponer la IA y qué debe revisar una persona.", "Escribe un límite verificable para el uso de IA."], "¿Qué parte de tu proceso seguiría necesitando evidencia humana?", "Mapa de tareas con apoyo, revisión y no automatización."),
  },
  {
    id: "modulo-02", week: 2, hours: 4,
    title: "Diseño de instrucciones contables",
    focus: "Construir prompts con contexto, datos permitidos, tarea, formato, restricciones y verificación; iterar con una rúbrica.",
    outcome: "Entregar una plantilla de prompt y una versión revisada con criterios visibles.",
    exerciseIds: ["prompt"], materialPath: "/docs/curso/modulo-02/README.md",
    guide: guide("Un prompt útil funciona como una hoja de trabajo: define el alcance antes de pedir una respuesta.", ["Especifica rol, contexto y datos ficticios permitidos.", "Pide una salida concreta que otra persona pueda revisar.", "Añade límites, dudas y una comprobación final."], "¿Tu instrucción permite distinguir hechos, supuestos y datos faltantes?", "Plantilla de prompt contable y una iteración mejorada."),
  },
  {
    id: "modulo-03", week: 3, hours: 4,
    title: "Herramientas, privacidad y uso seguro",
    focus: "Comparar herramientas según la tarea, reconocer datos personales y confidenciales, y revisar permisos antes de compartir información.",
    outcome: "Completar una matriz de selección de herramienta y una lista de control de privacidad.",
    exerciseIds: ["nomina"], materialPath: null,
    guide: guide("La primera decisión no es qué herramienta usar, sino qué datos nunca debes compartir.", ["Identifica datos personales, confidenciales y ficticios.", "Define el propósito, permisos y retención necesarios.", "Redacta una regla de minimización y una ruta de escalamiento."], "¿Podrías explicar por qué cada campo es necesario para la tarea?", "Matriz de herramienta y checklist de privacidad antes de compartir."),
  },
  {
    id: "modulo-04", week: 4, hours: 4,
    title: "Preparación de datos y clasificación",
    focus: "Revisar estructura y calidad de archivos; estandarizar campos; proponer categorías y apartar excepciones para revisión humana.",
    outcome: "Preparar un conjunto de práctica ordenado y un mapa de categorías con reglas y excepciones.",
    exerciseIds: ["clasificacion"], materialPath: null,
    guide: guide("La IA clasifica mejor cuando los datos tienen estructura y las excepciones están a la vista.", ["Revisa campos, formatos, duplicados y valores faltantes.", "Define categorías con una regla observable.", "Aparta casos ambiguos: no fuerces una clasificación."], "¿Qué dato te haría cambiar de categoría o pedir una revisión?", "Conjunto ordenado, mapa de categorías y lista de excepciones."),
  },
  {
    id: "modulo-05", week: 5, hours: 4,
    title: "Conciliación y automatización de flujos",
    focus: "Comparar libro y banco, separar coincidencias y partidas pendientes, y definir controles en el flujo de trabajo.",
    outcome: "Documentar una conciliación y un procedimiento con entradas, revisión, autorización y registro.",
    exerciseIds: ["conciliacion"], materialPath: null,
    guide: guide("Conciliar no es buscar una cifra parecida: es explicar cada diferencia con evidencia y responsable.", ["Alinea fechas, conceptos e importes de ambas fuentes.", "Separa coincidencias, pendientes y posibles comisiones.", "Diseña revisión, autorización y registro de ajustes."], "¿Puedes señalar qué falta registrar sin convertir una hipótesis en hecho?", "Conciliación documentada y procedimiento con controles."),
  },
  {
    id: "modulo-06", week: 6, hours: 4,
    title: "Balanzas e indicadores financieros",
    focus: "Comprobar sumas, interpretar variaciones y diferenciar una inconsistencia aritmética de una explicación contable.",
    outcome: "Crear una hoja de revisión con diferencia, hipótesis permitidas y verificaciones siguientes.",
    exerciseIds: ["balanza"], materialPath: null,
    guide: guide("Primero comprueba la aritmética; después formula hipótesis y nunca al revés.", ["Verifica sumas, signo, periodo y unidades.", "Describe la variación sin atribuirle una causa no demostrada.", "Anota la evidencia que resolvería cada hipótesis."], "¿Qué cálculo puedes confirmar y qué explicación sigue abierta?", "Hoja de revisión con diferencia, hipótesis y próximas verificaciones."),
  },
  {
    id: "modulo-07", week: 7, hours: 4,
    title: "Reportes y comunicación ejecutiva",
    focus: "Separar hechos, hipótesis, limitaciones y próximos pasos al convertir cifras en una explicación breve.",
    outcome: "Entregar un reporte ejecutivo de una página respaldado por los datos ficticios.",
    exerciseIds: ["reporte"], materialPath: null,
    guide: guide("Un reporte ejecutivo no dice todo: dice lo necesario, muestra el respaldo y deja claro qué falta.", ["Abre con el hallazgo y su impacto observable.", "Separa hechos, hipótesis y limitaciones.", "Cierra con una acción, responsable y fecha de revisión."], "¿Qué frase de tu reporte cambiaría si faltara una fuente?", "Reporte de una página con hechos, límites y próximos pasos."),
  },
  {
    id: "modulo-08", week: 8, hours: 4,
    title: "Auditoría, excepciones y anomalías",
    focus: "Usar patrones como señales para investigar, requerir evidencia y evitar conclusiones de fraude sin sustento.",
    outcome: "Documentar una anomalía con evidencia pendiente, riesgo y siguiente paso.",
    exerciseIds: ["analisis"], materialPath: null,
    guide: guide("Una anomalía es una señal de revisión, no una sentencia. Nora te ayudará a mantener esa diferencia.", ["Describe el patrón observado y su frecuencia.", "Estima el riesgo sin afirmar intención ni fraude.", "Pide evidencia, asigna un siguiente paso y conserva trazabilidad."], "¿Qué observaste directamente y qué estás suponiendo?", "Ficha de anomalía con evidencia pendiente, riesgo y acción."),
  },
  {
    id: "modulo-09", week: 9, hours: 4,
    title: "Investigación fiscal responsable en México",
    focus: "Precisar ejercicio y régimen; identificar datos faltantes; contrastar publicaciones vigentes y pedir revisión profesional.",
    outcome: "Completar una hoja de verificación de fuentes, faltantes y límites de la respuesta.",
    exerciseIds: ["isr", "resico", "nomina"], materialPath: null,
    guide: guide("En temas fiscales, una respuesta prudente comienza declarando el periodo, régimen y datos que faltan.", ["Define el supuesto fiscal y la fecha de vigencia.", "Contrasta fuentes oficiales y registra la versión consultada.", "Señala límites y deriva a revisión profesional cuando corresponda."], "¿Qué dato o fuente faltante impide orientar de forma responsable?", "Hoja de fuentes, datos faltantes, límites y derivación."),
  },
  {
    id: "modulo-10", week: 10, hours: 4,
    title: "Asistentes, gobernanza y proyecto integrador",
    focus: "Diseñar un procedimiento reutilizable con entradas, salidas, salvaguardas, métricas, revisión humana y escalamiento.",
    outcome: "Presentar un flujo de trabajo documentado y un resumen ejecutivo sobre un caso totalmente ficticio.",
    exerciseIds: ["prompt", "clasificacion", "conciliacion", "balanza", "reporte", "analisis", "isr", "resico", "nomina"], materialPath: null,
    guide: guide("El proyecto integrador une criterio, datos, controles y comunicación en un flujo que otra persona pueda auditar.", ["Define entradas, salida esperada y puntos de control.", "Asigna revisión humana, métricas y criterios de escalamiento.", "Prueba el flujo con un caso ficticio y documenta sus límites."], "¿Qué ocurre cuando la IA no tiene evidencia suficiente o propone algo inesperado?", "Flujo gobernado, resumen ejecutivo y registro de decisiones."),
  },
];
