export const PROMPT_RUBRIC = [
  { id: "rol", label: "Define el rol profesional", keywords: ["actúa como", "asume el rol", "eres contador"] },
  { id: "contexto", label: "Da contexto suficiente", keywords: ["empresa ficticia", "contexto", "escenario", "caso simulado"] },
  { id: "tarea", label: "Indica una tarea concreta", keywords: ["analiza", "clasifica", "concilia", "compara", "elabora"] },
  { id: "datos", label: "Limita la tarea a los datos disponibles", keywords: ["datos proporcionados", "información proporcionada", "movimientos", "cifras"] },
  { id: "formato", label: "Pide un formato de salida útil", keywords: ["tabla", "columnas", "reporte", "formato", "lista"] },
  { id: "verificación", label: "Pide verificación y límites explícitos", keywords: ["verifica", "fuente oficial", "no inventes", "indica incertidumbre", "señala lo que falta"] },
];

const choices = (values) => values.map(([id, label]) => ({ id, label }));

export const exercises = [
  {
    id: "prompt", category: "Fundamentos", kind: "prompt", time: "6 min",
    title: "Redacta un prompt contable útil",
    intro: "Pídele a una IA que revise movimientos simulados para preparar una conciliación. Un buen prompt acota la tarea, exige un formato y marca qué debe verificarse.",
    scenario: "Una empresa ficticia quiere comparar movimientos bancarios con su libro auxiliar. El expediente incluye una comisión bancaria simulada sin registrar.",
    rubric: PROMPT_RUBRIC,
    hint: "Incluye contexto, una instrucción concreta, el formato de salida y una regla para declarar dudas o datos faltantes.",
    solution: "Actúa como auxiliar contable. En el contexto de una microempresa ficticia, compara únicamente los movimientos bancarios y del libro auxiliar que te proporcionaré. Devuelve una tabla con fecha, importe, coincidencia o diferencia y explicación. No inventes registros; señala cualquier dato faltante y recomienda verificar las diferencias contra los comprobantes originales.",
    keywords: ["compara", "tabla", "no inventes", "verifica"],
  },
  {
    id: "clasificacion", category: "Operación contable", kind: "quiz", time: "4 min",
    title: "Clasifica una compra de oficina",
    intro: "Practica la clasificación inicial de una operación; no sustituye la política contable de una entidad.",
    scenario: "Caso ficticio: se paga con tarjeta $620 MXN por papelería de uso inmediato. El comprobante simulado está disponible y la entidad usa una cuenta de gastos de oficina.",
    question: "¿Qué clasificación inicial coincide mejor con la información del caso?",
    choices: choices([
      ["gasto", "Registrar un gasto de oficina por $620 y la salida de bancos, sujeto a revisar el comprobante."],
      ["ingreso", "Registrar un ingreso por venta porque hubo un movimiento bancario."],
      ["activo", "Registrar automáticamente un activo fijo por tratarse de una compra."],
    ]),
    answer: "gasto",
    hint: "Considera el uso inmediato del artículo y separa la naturaleza de la compra del medio de pago.",
    explanation: "La opción de gasto de oficina es la clasificación inicial descrita por el caso. En un registro real se revisarían comprobante, política contable, impuestos y plan de cuentas aplicable.",
  },
  {
    id: "conciliacion", category: "Operación contable", kind: "reconciliation", time: "5 min",
    title: "Encuentra la diferencia bancaria",
    intro: "Compara los dos lados del expediente simulado y localiza una partida que aparece solo en el banco.",
    scenario: "Caso educativo: compara los movimientos del banco con el libro auxiliar. Hay cuatro coincidencias y una comisión bancaria simulada pendiente de registro.",
    bank: [
      ["02 sep", "Cobro INV-101", "+$3,500"], ["03 sep", "Abono AR-204", "+$2,450"],
      ["04 sep", "Comisión bancaria", "−$87"], ["05 sep", "Papelería", "−$620"], ["06 sep", "Servicio digital", "−$420"],
    ],
    ledger: [
      ["02 sep", "Cobro INV-101", "+$3,500"], ["03 sep", "Abono AR-204", "+$2,450"],
      ["05 sep", "Papelería", "−$620"], ["06 sep", "Servicio digital", "−$420"],
    ],
    question: "¿Qué movimiento del banco aún no aparece en el libro auxiliar?",
    choices: choices([
      ["fee", "Comisión bancaria simulada por $87 MXN."],
      ["sale", "Venta de mostrador ficticia POS-44 por $1,850 MXN."],
      ["vendor", "Transferencia de prueba PV-09 por $1,130 MXN."],
    ]),
    answer: "fee",
    hint: "Busca una partida que esté en el extracto bancario simulado pero no en la lista del libro.",
    explanation: "La comisión de $87 aparece en el banco y falta en el libro. Antes de registrar un ajuste real, se revisaría el estado de cuenta, el comprobante y el tratamiento contable/fiscal aplicable.",
  },
  {
    id: "balanza", category: "Operación contable", kind: "quiz", time: "4 min",
    title: "Lee una balanza de comprobación",
    intro: "Detecta una inconsistencia aritmética sin forzar ni alterar saldos para que cuadren.",
    scenario: "Caso de práctica: total de cargos $86,500 MXN y total de abonos $84,500 MXN.",
    question: "¿Cuál es la conclusión inicial más prudente?",
    choices: choices([
      ["difference", "No cuadra: los cargos exceden a los abonos en $2,000; hay que rastrear el origen."],
      ["balanced", "Está equilibrada porque ambos totales son cercanos."],
      ["adjust", "Registrar automáticamente $2,000 en ingresos para igualar los totales."],
    ]),
    answer: "difference",
    hint: "Compara los totales exactamente y evita proponer un asiento de ajuste sin evidencia.",
    explanation: "La diferencia aritmética es $2,000 MXN a favor de los cargos. Es un indicio para revisar captura, clasificación y mayor; no indica por sí sola cuál cuenta corregir.",
  },
  {
    id: "reporte", category: "Análisis", kind: "written", time: "6 min",
    title: "Prepara un reporte ejecutivo breve",
    intro: "Resume cifras ficticias para una persona directiva, separando hechos, hipótesis y siguientes revisiones.",
    scenario: "Caso simulado de septiembre: ventas $125,000 MXN; costos $72,000; gastos operativos $39,000. En agosto, las ventas fueron $118,000 y los gastos $35,000. No hay detalle de impuestos ni notas sobre eventos extraordinarios.",
    rubric: [
      { id: "hechos", label: "Resume cifras observadas sin cambiar los datos", keywords: ["125,000", "72000", "72,000", "39,000", "118,000"] },
      { id: "comparacion", label: "Compara septiembre con agosto", keywords: ["agosto", "comparación", "comparado", "respecto"] },
      { id: "limites", label: "Separa hechos de hipótesis y reconoce lo que falta", keywords: ["no se cuenta", "falta", "hipótesis", "supuesto", "no disponible"] },
      { id: "accion", label: "Propone una verificación siguiente", keywords: ["verificar", "revisar", "confirmar", "detalle", "comprobantes"] },
    ],
    hint: "Incluye un resumen numérico, una comparación intermensual y una limitación explícita antes de recomendar qué revisar.",
    solution: "En septiembre el caso registra ventas por $125,000 MXN, costos por $72,000 y gastos operativos por $39,000. Las ventas superan los $118,000 reportados en agosto, mientras los gastos pasan de $35,000 a $39,000. No se proporcionan notas de eventos extraordinarios ni detalle tributario, por lo que no corresponde atribuir causas. Siguiente paso: revisar variaciones por cuenta y comprobantes antes de emitir conclusiones.",
    keywords: ["agosto", "falta", "verificar"],
  },
  {
    id: "analisis", category: "Análisis", kind: "quiz", time: "4 min",
    title: "Investiga una anomalía financiera",
    intro: "Identifica un patrón inusual y formula un paso de revisión, sin confundir una alerta con una conclusión de fraude.",
    scenario: "Datos ficticios: el gasto mensual en servicios digitales pasó de $4,200 a $12,600 MXN. No se adjuntaron contratos, facturas ni cambios de operación.",
    question: "¿Qué respuesta inicial es más responsable?",
    choices: choices([
      ["review", "Marcar la variación como alerta, comparar cargos individuales y solicitar soporte antes de concluir."],
      ["fraud", "Afirmar que hubo fraude y registrar una pérdida definitiva."],
      ["ignore", "Ignorar la variación porque las herramientas de IA pueden equivocarse."],
    ]),
    answer: "review",
    hint: "La detección encuentra excepciones; la evidencia y el juicio profesional determinan qué significan.",
    explanation: "El aumento justifica análisis y verificación de respaldo. No basta para afirmar fraude: puede haber renovación, duplicidad, cambio de plan o error de captura.",
  },
  {
    id: "isr", category: "Impuestos MX", kind: "quiz", time: "4 min",
    title: "ISR: pide evidencia, no una respuesta inventada",
    intro: "Caso didáctico mexicano con importes ficticios. La práctica se centra en pedir información suficiente y validar el marco aplicable.",
    scenario: "Una microempresa simulada pide a una herramienta que explique diferencias entre dos cifras de ISR, pero no indica régimen, ejercicio fiscal, tipo de contribuyente ni documentos de soporte.",
    question: "¿Qué instrucción es más segura para la herramienta?",
    choices: choices([
      ["context", "Solicitar los datos faltantes, identificar el ejercicio/régimen y verificar criterios en fuentes oficiales vigentes; no calcular con supuestos ocultos."],
      ["guess", "Elegir la cifra menor y redactar una explicación convincente."],
      ["old", "Aplicar automáticamente una tasa recordada de un ejercicio anterior."],
    ]),
    answer: "context",
    hint: "El impuesto depende de contexto y reglas aplicables; el ejercicio no proporciona información suficiente para calcularlo.",
    explanation: "La respuesta responsable hace explícitos los faltantes y requiere verificación en fuentes oficiales actuales y revisión profesional. Este ejercicio no determina impuestos ni ofrece asesoría.",
  },
  {
    id: "resico", category: "Impuestos MX", kind: "quiz", time: "4 min",
    title: "RESICO: valida antes de orientar",
    intro: "Escenario educativo con una empresa ficticia. Practica cómo pedir una revisión, no cómo emitir una conclusión de elegibilidad.",
    scenario: "Una persona ficticia pregunta a una IA si puede tributar en RESICO. Solo comparte una estimación de ingresos; no confirma actividad, requisitos, periodo ni situación ante el SAT.",
    question: "¿Cuál es el mejor siguiente paso?",
    choices: choices([
      ["verify", "No asumir elegibilidad; reunir los datos pertinentes y contrastar requisitos vigentes en material oficial del SAT con apoyo profesional."],
      ["eligible", "Afirmar que toda persona debajo de una cantidad genérica puede entrar al régimen."],
      ["submit", "Presentar una declaración de prueba con la información incompleta."],
    ]),
    answer: "verify",
    hint: "La cifra de ingresos por sí sola no demuestra que se cumplan todos los requisitos vigentes.",
    explanation: "La práctica no decide si alguien es elegible. La regla puede depender de requisitos y circunstancias que deben revisarse en las disposiciones oficiales aplicables al periodo.",
  },
  {
    id: "nomina", category: "Impuestos MX", kind: "quiz", time: "4 min",
    title: "Nómina: protege datos personales",
    intro: "Caso ficticio de nómina. Evalúa privacidad antes de usar una herramienta generativa externa.",
    scenario: "Un equipo quiere pegar recibos de nómina y nombres de empleados en un asistente público para resumir incidencias.",
    question: "¿Qué alternativa protege mejor la información?",
    choices: choices([
      ["anonymize", "No cargar recibos identificables; usar un conjunto de prueba anonimizado y autorizado, verificar políticas internas y revisar cualquier resultado."],
      ["paste", "Pegar los recibos completos para que el asistente tenga más contexto."],
      ["mask", "Cambiar solo los nombres y cargar el resto de los recibos sin revisar identificadores."],
    ]),
    answer: "anonymize",
    hint: "Los recibos pueden incluir identificadores y datos financieros aunque se retire el nombre.",
    explanation: "La práctica más segura evita compartir información identificable, usa datos sintéticos/autorizados y sigue los controles internos. El caso no procesa nóminas reales ni calcula retenciones.",
  },
];

export const categories = ["Fundamentos", "Operación contable", "Análisis", "Impuestos MX"];
