export const GLOSSARY = [
  { term: "IA generativa", definition: "Tecnología que produce texto, imágenes o propuestas a partir de patrones aprendidos.", example: "Puede proponer una clasificación, pero no confirma que sea correcta.", check: "¿Qué evidencia revisarás antes de aceptar la propuesta?" },
  { term: "Prompt", definition: "Instrucción o petición que se da a una herramienta de IA.", example: "‘Explica esta diferencia con estos datos ficticios y señala qué falta’ es más útil que ‘analiza esto’.", check: "¿La petición indica tarea, contexto y resultado esperado?" },
  { term: "Respuesta", definition: "Resultado que la herramienta propone después de interpretar una instrucción.", example: "Una respuesta puede sonar convincente y aun así contener una cifra inventada.", check: "¿Qué parte es un hecho y qué parte necesita confirmación?" },
  { term: "Contexto", definition: "Información que permite entender el propósito, alcance y situación de una tarea.", example: "El periodo, la moneda y el destinatario cambian cómo se interpreta un reporte.", check: "¿Qué dato faltante podría cambiar la respuesta?" },
  { term: "Restricción", definition: "Límite explícito sobre datos, alcance, formato o acciones permitidas.", example: "‘Usa solo datos ficticios y no inventes información’ es una restricción.", check: "¿La herramienta sabe qué no debe hacer?" },
  { term: "Dato personal", definition: "Información que identifica o puede identificar a una persona.", example: "Nombre, CURP, RFC, domicilio y cuenta bancaria.", check: "¿Este campo es necesario para la actividad?" },
  { term: "Minimización", definition: "Principio de usar o compartir solo los datos indispensables.", example: "Para practicar una clasificación basta una etiqueta ficticia, no el expediente completo.", check: "¿Puedes quitar este campo sin perder el objetivo?" },
  { term: "Permiso", definition: "Autorización que determina quién puede acceder, modificar o aprobar una acción.", example: "Una persona puede revisar un borrador sin tener permiso para registrar un ajuste.", check: "¿Quién puede ver, cambiar y aprobar este resultado?" },
  { term: "Campo", definition: "Columna o espacio con un significado definido dentro de un documento.", example: "Fecha, concepto e importe son campos de una transacción.", check: "¿El encabezado y el formato del campo son claros?" },
  { term: "Categoría", definition: "Grupo al que se asigna un registro usando una regla observable.", example: "‘Gasto operativo’ puede ser una categoría si existe una regla para asignarla.", check: "¿Otra persona aplicaría la misma regla?" },
  { term: "Excepción", definition: "Caso que no puede resolverse con seguridad usando la información disponible.", example: "Un concepto ambiguo se envía a revisión en lugar de forzar una categoría.", check: "¿Qué evidencia permitiría resolverlo?" },
  { term: "Coincidencia", definition: "Registro de dos fuentes que coincide según criterios definidos.", example: "Misma fecha, referencia e importe en banco y libro auxiliar.", check: "¿Qué criterios usaste para afirmar que coincide?" },
  { term: "Partida pendiente", definition: "Diferencia que todavía necesita registro, evidencia o autorización.", example: "Una comisión bancaria identificada pero aún no registrada.", check: "¿Quién debe revisar o autorizar el siguiente paso?" },
  { term: "Control", definition: "Regla o punto de revisión que ayuda a prevenir errores y conservar trazabilidad.", example: "Pedir aprobación humana antes de registrar un ajuste.", check: "¿Qué ocurre si el control detecta un problema?" },
  { term: "Diferencia", definition: "Resultado de comparar dos valores, saldos o totales.", example: "La resta entre el saldo del banco y el saldo del libro.", check: "¿El cálculo, signo y periodo fueron comprobados?" },
  { term: "Variación", definition: "Cambio observado entre dos periodos, saldos o situaciones.", example: "Un ingreso es mayor este mes que el mes anterior.", check: "¿Observas el cambio sin atribuir todavía una causa?" },
  { term: "Hipótesis", definition: "Explicación provisional que requiere evidencia para confirmarse o descartarse.", example: "Un cobro duplicado podría explicar una variación, pero debe investigarse.", check: "¿Qué evidencia probaría o refutaría la hipótesis?" },
  { term: "Hecho", definition: "Afirmación respaldada directamente por los datos o una fuente identificada.", example: "El saldo registrado el 31 de enero es de $5,000 ficticios.", check: "¿Puedes señalar la fila o fuente que lo respalda?" },
  { term: "Próximo paso", definition: "Acción concreta que reduce la incertidumbre o mueve el caso hacia una decisión.", example: "Solicitar la factura y asignar una persona revisora.", check: "¿Tiene responsable y fecha?" },
  { term: "Señal", definition: "Patrón que se aparta de lo esperado y merece revisión.", example: "Un movimiento inusualmente alto respecto de la línea base.", check: "¿Es una señal o ya tienes evidencia de una causa?" },
  { term: "Riesgo", definition: "Posible impacto si una situación no se aclara o controla.", example: "Registrar un ajuste sin autorización puede afectar la trazabilidad.", check: "¿Qué podría ocurrir y qué control lo reduce?" },
  { term: "Evidencia", definition: "Dato, registro o fuente que permite sostener o revisar una afirmación.", example: "Factura ficticia, conciliación, regla publicada o registro de aprobación.", check: "¿La evidencia es suficiente, pertinente y vigente?" },
  { term: "Periodo", definition: "Intervalo o ejercicio al que corresponde un dato, regla o reporte.", example: "Enero de 2026 o ejercicio fiscal 2025.", check: "¿La fuente aplica exactamente a este periodo?" },
  { term: "Régimen", definition: "Situación fiscal que determina reglas y obligaciones aplicables.", example: "Una orientación para RESICO no se traslada automáticamente a otro régimen.", check: "¿El régimen está identificado y verificado?" },
  { term: "Fuente oficial", definition: "Publicación de la autoridad o entidad responsable que se consulta y registra.", example: "Una disposición vigente de una autoridad fiscal.", check: "¿Conoces la fecha y jurisdicción de la fuente?" },
  { term: "Entrada", definition: "Dato o documento permitido que inicia un procedimiento o flujo.", example: "Un CSV ficticio con encabezados y periodo definidos.", check: "¿La entrada está completa y autorizada?" },
  { term: "Salida", definition: "Resultado esperado de un procedimiento, con formato y criterios definidos.", example: "Una tabla de pendientes con responsable y siguiente paso.", check: "¿La salida puede ser revisada por otra persona?" },
  { term: "Gobernanza", definition: "Conjunto de reglas para permisos, revisión, métricas, trazabilidad y escalamiento.", example: "Detener un flujo ante datos sensibles y pedir aprobación humana.", check: "¿Quién puede aprobar, detener o auditar el flujo?" },
];

export function findGlossaryEntry(term) {
  return GLOSSARY.find((entry) => entry.term === term);
}
